# Generated by Django 5.2 on 2025-05-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_following'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to='posts.post'),
        ),
    ]
